language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install

script:
  - phpunit --version
  - phpunit
